[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
jupiter = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
vaults = "STRK2VEGPAKstk6S6k5Cpin6uGtSDQkvanTaXUeaTNj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deploy/authority.json"

[scripts]
test = "yarn setup:mainnet"
test-sdk = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:sdk; pkill solana-test-validator)"
test-vaults = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:vaults; pkill solana-test-validator)"
