[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaults = "STRK2VEGPAKstk6S6k5Cpin6uGtSDQkvanTaXUeaTNj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deploy/authority.json"

[scripts]
test = "yarn setup:mainnet"
# TODO: Fix errors in these commands
test-vaults = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:vaults; pkill solana-test-validator)"
test-sdk = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:sdk; pkill solana-test-validator)"
