[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
# NOTE: Running anchor keys sync updates this ID, which is not
#       correct as this needs to track the Jupiter mainnet program ID
jupiter = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
transfer_hook = "3Mbtr8yzqLUuBZVSefrVtAPmgNLFutEXeRWJNATsKU5z"
vaults = "HULUoT5PHWhoj9ELE1XHFo8jJqHj89uGwWNq3Skrja28"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deploy/deployer.json"

[scripts]
test = "yarn test:transferHook"
test-vaults = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:vaults; pkill solana-test-validator)"
test-transferHook = "(anchor localnet > /dev/null &) && sleep 2 && (yarn test:transferHook; pkill solana-test-validator)"
