[env]
OPENSSL_STATIC = "1"
OPENSSL_DIR = "/opt/homebrew/opt/openssl@3"
OPENSSL_LIB_DIR = "/opt/homebrew/opt/openssl@3/lib"
OPENSSL_INCLUDE_DIR = "/opt/homebrew/opt/openssl@3/include"
OPENSSL_NO_VENDOR = "1"
