# All whitelisted tokens
- alias: BTC/USD
  id: e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43
  time_difference: 5
  # price_deviation: 0.1
  # confidence_ratio: 0.2
  # early_update:
  #   time_difference: 2
  #   price_deviation: 0.05
  #   confidence_ratio: 0.1
