services:
  price-pusher:
    image: public.ecr.aws/pyth-network/xc-price-pusher:v9.1.0
    restart: always
    # environment:
    #   - SOLANA_RPC_URL=${SOLANA_RPC_URL}
    #   - SHARD_ID=${SHARD_ID}
    command:
      - "npm"
      - "run"
      - "start"
      - "--"
      - "solana"
      - "--endpoint"
      - ${SOLANA_RPC_URL}
      - "--shard-id"
      - ${SHARD_ID}
      - "--price-config-file"
      - "/price_config"
      - "--price-service-endpoint"
      - ${PRICE_SERVICE_ENDPOINT}
      - "--pyth-contract-address"
      - "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
      - "--pushing-frequency"
      - "30"
      - "--polling-frequency"
      - "5"
    configs:
      - price_config
configs:
  price_config:
    file: ./config.yaml
