#!/bin/sh

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

# Check if program name is provided
if [ -z "$1" ]; then
    echo "Error: Program name not provided."
    echo "Usage: $0 <vaults|transfer_hook>"
    exit 1
fi

PROGRAM_NAME=$1
SO_FILE_PATH=""
PROGRAM_ID_PATH=""

if [ "$PROGRAM_NAME" = "vaults" ]; then
    SO_FILE_PATH="target/deploy/vaults.so"
    PROGRAM_ID_PATH="target/deploy/vaults-keypair.json"
elif [ "$PROGRAM_NAME" = "transfer_hook" ]; then
    SO_FILE_PATH="target/deploy/transfer_hook.so"
    PROGRAM_ID_PATH="target/deploy/transfer_hook-keypair.json"
else
    echo "Error: Invalid program name '$PROGRAM_NAME'."
    echo "Usage: $0 <vaults|transfer_hook>"
    exit 1
fi

# NOTE: Can not use verifiable build unless anchor fixes their issue
#       https://github.com/coral-xyz/anchor/issues/3585
# solana -u $MAINNET_RPC program deploy target/verifiable/vaults.so -k ./deploy/authority.json --buffer ./deploy/buffer.json --program-id ./target/deploy/vaults-keypair.json
solana -u $MAINNET_RPC program deploy "$SO_FILE_PATH" -k ./deploy/authority.json --buffer ./deploy/buffer.json --program-id "$PROGRAM_ID_PATH"
