#!/bin/sh

# Parse command line arguments
VERIFIABLE=false
PROGRAM_NAME=""

while getopts "v" opt; do
  case $opt in
    v)
      VERIFIABLE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Shift the options out of the argument list
shift $((OPTIND-1))

if [ -z "$1" ]; then
    echo "Usage: $0 [-v] <program-name>"
    echo "  -v: Deploy in verifiable mode"
    exit 1
fi

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

PROGRAM_NAME=$1

if [ "$VERIFIABLE" = true ]; then
    echo "Deploying in verifiable mode..."
    anchor deploy -p $PROGRAM_NAME -v --provider.cluster $MAINNET_RPC
else
    echo "Deploying in standard mode..."
    anchor deploy -p $PROGRAM_NAME --provider.cluster $MAINNET_RPC
fi
