#!/bin/sh

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

# Set ANCHOR_PROVIDER_URL to MAINNET_RPC
export ANCHOR_PROVIDER_URL=$MAINNET_RPC

# Function to run a specific test
run_test() {
    local test_name=$1
    case $test_name in
        "vaults")
            cargo test -p vaults --lib
            ;;
        "transferHook")
            yarn test:transferHook
            ;;
        "vaults:initialize")
            yarn test:vaults:initialize
            ;;
        "vaults:tokenWhitelist")
            yarn test:vaults:tokenWhitelist
            ;;
        "vaults:managerWhitelist")
            yarn test:vaults:managerWhitelist
            ;;
        "vaults:userWhitelist")
            yarn test:vaults:userWhitelist
            ;;
        "vaults:createVault")
            yarn test:vaults:createVault
            ;;
        "vaults:createVaultEnhanced")
            yarn test:vaults:createVaultEnhanced
            ;;
        "vaults:deposit")
            yarn test:vaults:deposit
            ;;
        "vaults:investorTypeValidation")
            yarn test:vaults:investorTypeValidation
            ;;
        "vaults:withdraw")
            yarn test:vaults:withdraw
            ;;
        "vaults:depositWithdrawEnhanced")
            yarn test:vaults:depositWithdrawEnhanced
            ;;
        "vaults:pause")
            yarn test:vaults:pauseStarke
            ;;
        "vaults:vtoken")
            yarn test:vaults:vtokenTransferrability
            ;;
        "vaults:swap")
            yarn test:vaults:swap
            ;;
        "vaults:integration")
            yarn test:vaults:integrationTest
            ;;
        "vaults:closeVault")
            yarn test:vaults:closeVault
            ;;
        "vaults:info")
            yarn test:vaults:info
            ;;
        *)
            echo "Unknown test: $test_name"
            exit 1
            ;;
    esac
}

# If a test name is provided, run only that test
if [ ! -z "$1" ]; then
    run_test "$1"
else
    # Run all tests in order
    echo "Running all tests..."
    # yarn test:transferHook
    # yarn test:vaults:initialize
    # yarn test:vaults:tokenWhitelist
    # yarn test:vaults:managerWhitelist
    # yarn test:vaults:createVault
    # yarn test:vaults:deposit
fi
