#!/bin/sh

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

anchor upgrade -p STRK2VEGPAKstk6S6k5Cpin6uGtSDQkvanTaXUeaTNj ./target/verifiable/vaults.so --provider.cluster $MAINNET_RPC
