#!/bin/sh

# Parse command line arguments
VERIFIABLE=false
PROGRAM_ID=""
PROGRAM_NAME=""

while getopts "v" opt; do
  case $opt in
    v)
      VERIFIABLE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# Shift the options out of the argument list
shift $((OPTIND-1))

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

# Check if program name is provided
if [ -z "$1" ]; then
    echo "Error: Program name not provided."
    echo "Usage: $0 [-v] <vaults|transfer_hook> <program-id>"
    echo "  -v: Upgrade in verifiable mode"
    exit 1
fi

PROGRAM_NAME=$1
shift

# Check if program ID is provided
if [ -z "$1" ]; then
    echo "Error: Program ID not provided."
    echo "Usage: $0 [-v] <vaults|transfer_hook> <program-id>"
    echo "  -v: Upgrade in verifiable mode"
    exit 1
fi

PROGRAM_ID=$1

# Set the correct .so file path based on program name
if [ "$PROGRAM_NAME" = "vaults" ]; then
    SO_FILE_PATH="vaults.so"
elif [ "$PROGRAM_NAME" = "transfer_hook" ]; then
    SO_FILE_PATH="transfer_hook.so"
else
    echo "Error: Invalid program name '$PROGRAM_NAME'."
    echo "Usage: $0 [-v] <vaults|transfer_hook> <program-id>"
    echo "  -v: Upgrade in verifiable mode"
    exit 1
fi

if [ "$VERIFIABLE" = true ]; then
    echo "Upgrading in verifiable mode..."
    anchor upgrade -p $PROGRAM_ID ./target/verifiable/$SO_FILE_PATH --provider.cluster $MAINNET_RPC
else
    echo "Upgrading in standard mode..."
    anchor upgrade -p $PROGRAM_ID ./target/deploy/$SO_FILE_PATH --provider.cluster $MAINNET_RPC
fi
