#!/bin/sh

# Check if RPC endpoint is provided
if [ -z "$MAINNET_RPC" ]; then
    echo "Error: MAINNET_RPC environment variable is not set"
    echo "Please set it using: export MAINNET_RPC=<your-rpc-endpoint>"
    exit 1
fi

# NOTE: Can not use verifiable build unless anchor fixes their issue
#       https://github.com/coral-xyz/anchor/issues/3585
# anchor upgrade -p Fe8j1bGgJfrdGGpiVa39cP98TvENbgmv95eYhvtiKVR5 ./target/verifiable/vaults.so --provider.cluster $MAINNET_RPC
anchor upgrade -p Fe8j1bGgJfrdGGpiVa39cP98TvENbgmv95eYhvtiKVR5 ./target/deploy/vaults.so --provider.cluster $MAINNET_RPC
